services:
  mockrr:
    # Apache/2.4.59 (Debian) PHP/8.3.6
    image: php:apache-bookworm
    restart: always
    ports:
      - "8888:80"
    volumes:
      # Map server config, setting the path to the DocumentRoot
      - ./.docker/apache2.conf:/etc/apache2/sites-available/000-default.conf
      # Map current folder to container; see the examples folder for index.php
      - .:/var/www/mockrr
